version: '3.8'
services:
  app:
    container_name: auth-nodejs-auth
    image: auth-nodejs-auth:lts
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - .:/app
  db:
    container_name: auth-nodejs-db
    image: postgres:lts
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'